version: "3.8"
networks:
  keg-hub-net:
    external: true
services:
  keg-deploy:
    image: ${KEG_IMAGE_FROM}
    container_name: ${CONTAINER_NAME}
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - KEG_BASE_IMAGE
        - DOC_APP_PATH
        - AWS_CLI_VERSION
        - GIT_APP_URL
        - GIT_APP_BRANCH
        - TF_CLI_VERSION
        - TF_RELEASE_URL
    environment:
      - DOC_APP_PATH
      - DOC_MOUNTED_PATH
      - DOC_TERRAFORM_PATH
      - KEG_DOCKER_EXEC
      - KEG_DEPLOY_CMD
      - KEG_EXEC_CMD
      - ENV
      - NODE_ENV
      - CONTAINER_NAME
      - TF_VAR_aws_region
      - TF_VAR_target_group_port
      - TF_VAR_health_check_port
      - TF_VAR_health_check_path
    labels:
      - com.keg.env.context=keg-deploy
      - com.keg.path.context=${KEG_CONTEXT_PATH}
      - com.keg.path.container=${DOC_APP_PATH}
      - com.keg.path.compose=${KEG_COMPOSE_DEFAULT}
      - com.keg.path.values=${KEG_VALUES_FILE}
      - com.keg.path.docker=${KEG_DOCKER_FILE}
    volumes:
      - ${KEG_AWS_CREDS_PATH}:${DOC_AWS_CREDS_PATH}:ro
