env:

  # --- KEG-CLI ENV CONTEXT --- #
  KEG_DOCKER_FILE: "{{ cli.taps.deploy.path }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.deploy.path }}/container/values.yml"
  KEG_MUTAGEN_FILE: "{{ cli.taps.deploy.path }}/container/mutagen.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.deploy.path }}/container/docker-compose.yml"

  # Should be set dynamically to the app 
  KEG_CONTEXT_PATH: "{{ cli.taps.deploy.path }}"
  DOC_APP_PATH: /keg/app

  # Turn off adding an injected compose config for keg-proxy
  KEG_NO_INJECTED_COMPOSE: true

  # Turn off using the keg-proxy
  KEG_USE_PROXY: false

  # Turn off auto-creating a keg-proxy sync
  # KEG_AUTO_SYNC: false

  # Don't run the keg exec command within the container when attaching
  KEG_EXEC_CMD: false

  # Command type to be run when the the deploy container starts
  KEG_DEPLOY_CMD: cli

  # The aws region is required by the provisioner, and not loaded from the config
  # So we set it here to allow it to be overwritten
  # KEG_AWS_REGION: us-west-2

  # Add a custom mounted folder into the docker container
  # Must set the KEG_<NAME>_PATH env with a local path
  # Will be mounted to /keg/mounted within the container
  # Example => KEG_AWS_CREDS_PATH: "/Users/user-name/.aws"
  DOC_AWS_CREDS_PATH: /root/.aws
  DOC_MOUNTED_PATH: /keg/mounted
  DOC_TERRAFORM_PATH: /keg/terraform

  KEG_BASE_IMAGE: docker.io/library/node:14.16.0-alpine
  KEG_IMAGE_FROM: ghcr.io/simpleviewinc/keg-deploy:master

  # --- DOCKER ENV CONTEXT --- #
  AWS_CLI_VERSION: 1.16.278
  TF_CLI_VERSION: 0.12.28
  TF_RELEASE_URL: "https://releases.hashicorp.com/terraform"

  # --- GENERAL CONTEXT ENVs --- #
  IMAGE: keg-deploy
  CONTAINER_NAME: keg-deploy
  VERSION: 1.0.0

  # Git app url in github
  GIT_APP_URL: https://github.com/simpleviewinc/keg-deploy.git
  GIT_APP_BRANCH: master